[versions]
androidx-appcompat = "1.6.1" # https://developer.android.com/jetpack/androidx/releases/appcompat
androidx-browser = "1.5.0" # https://developer.android.com/jetpack/androidx/releases/browser
androidx-constraintlayout = "2.1.4" # https://developer.android.com/jetpack/androidx/releases/constraintlayout
androidx-core = "1.9.0" # https://developer.android.com/jetpack/androidx/releases/core
androidx-core-splashscreen = "1.0.0" # https://developer.android.com/jetpack/androidx/releases/core
androidx-fragment = "1.6.0-alpha05" # https://developer.android.com/jetpack/androidx/releases/fragment
androidx-lifecycle = "2.5.1" # https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-recyclerview = "1.2.1" # https://developer.android.com/jetpack/androidx/releases/recyclerview
androidx-room = "2.5.0" # https://developer.android.com/jetpack/androidx/releases/room
androidx-swiperefreshlayout = "1.2.0-alpha01" # https://developer.android.com/jetpack/androidx/releases/swiperefreshlayout
androidx-viewpager = "1.1.0-beta01" # https://developer.android.com/jetpack/androidx/releases/viewpager2
beagle = "2.9.0" # https://github.com/pandulapeter/beagle/releases
bumptech-glide = "4.14.2" # https://github.com/bumptech/glide/releases
google-android-material = "1.8.0" # https://github.com/material-components/material-components-android/releases
gradle = "7.4.1" # https://developer.android.com/studio/releases/gradle-plugin
jvm-target = "1.8" # https://kotlinlang.org/docs/gradle.html#check-for-jvm-target-compatibility-of-related-compile-tasks
koin = "3.3.3" # https://github.com/InsertKoinIO/koin/tags
kotlin = "1.8.10" # https://kotlinlang.org/docs/releases.html#release-details
kotlin-coroutines = "1.6.4" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlin-ksp = "1.8.10-1.0.9" # https://github.com/google/ksp/releases
photoview = "2.3.0" # https://github.com/Baseflow/PhotoView/tags
square-moshi = "1.14.0" # https://github.com/square/moshi/tags
square-okhttp = "4.10.0" # https://github.com/square/okhttp/tags
square-retrofit = "2.9.0" # https://github.com/square/retrofit/tags
theapache64-retrosheet = "2.0.1" # https://github.com/theapache64/retrosheet/releases

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "androidx-fragment" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-codegen = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-viewpager = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager" }
beagle = { module = "io.github.pandulapeter.beagle:ui-drawer", version.ref = "beagle" }
beagle-crashLogger = { module = "io.github.pandulapeter.beagle:log-crash", version.ref = "beagle" }
bumptech-glide = { module = "com.github.bumptech.glide:glide", version.ref = "bumptech-glide" }
bumptech-glide-codegen = { module = "com.github.bumptech.glide:ksp", version.ref = "bumptech-glide" }
bumptech-glide-okhttp = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "bumptech-glide" }
google-android-material = { module = "com.google.android.material:material", version.ref = "google-android-material" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
square-moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "square-moshi" }
square-moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "square-moshi" }
square-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "square-okhttp" }
square-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "square-retrofit" }
square-retrofit-converter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "square-retrofit" }
theapache64-retrosheet = { module = "com.github.theapache64:retrosheet", version.ref = "theapache64-retrosheet" }